[package]
name = "catppuccin-egui"
version = "2.0.0"
authors = ["Sam Nystrom <samuel.l.nystrom@gmail.com>"]
edition = "2021"
description = "Soothing pastel theme for egui."
documentation = "https://docs.rs/catppuccin-egui/"
readme = "README.md"
homepage = "https://github.com/catppuccin/egui"
repository = "https://github.com/catppuccin/egui"
license = "MIT"
keywords = ["egui", "catppuccin", "theme", "gui"]
categories = ["gui"]
exclude = ["assets/"]

[dependencies]
bevy_egui = "0.19"

[dev-dependencies]
eframe = "0.21"
